import React from 'react';
import type { Metadata } from "next";
import "./globals.css";
import styles from "./page.module.scss";

export const metadata: Metadata = {
  title: "URL simplifier Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className={styles.main}>
          {children}
        </main>
      </body>
    </html>
  );
}
